### ISSUE TITLE
Çoğu dosyada bozulma.

### ISSUE THREAD

**Issue by inoaa79** [OgnitorenKs/OgnitorenKs.Toolbox#2]
Ben mi yanlış görüyorum yoksa dosyalarda karakter hatası mı var? 
Örneğin :
https://github.com/OgnitorenKs/OgnitorenKs.Toolbox/blob/main/OgnitorenKs.Toolbox.bat 
12. Satır: Hazrlayan: Hseyin UZUNYAYLA / OgnitorenKs
Şeklinde gözüküyor. Eğer sizde de böyle ise elle yükledeysiniz git cli ile yüklemeyi deneyebilirsiniz.

Ayrıca inanılmaz muhteşem bir tool. Profilimde yer vereceğim. Ellerinize sağlık!

**Comment by OgnitorenKs** [comment]
Teşekkür ederim.
Hocam karakterlerin düzgün gözükmesi için Notepad++ > Kodlama > Karakter Takımı > Türkçe > OEM857 olarak seçilmesi gerekmektedir. Github'da bunların Notepad++ gibi düzeltme şansımız var mı bilmiyorum.

**Comment by inoaa79** [comment]
Dosyaları GitHub'a nasıl yüklüyorsunuz?

**Comment by OgnitorenKs** [comment]
Github uygulaması üzerinden.
